### ISSUE TITLE
Seeing some 403s in skill logs

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist-skills/docker-build-skill#14]
What I'm actually testing here is configuring the docker build skill to see Pushes that do NOT contain Dockerfiles.  However, I'm seeing these skills running forever because internally, there are errors like:

```
2020-05-08 16:17:59.873 ERROR: [error] Error occurred sending message: 403 undefined: Getting metadata from plugin failed with error: Could not refresh access token: A Forbidden error was returned while attempting to retrieve an access token for the Compute Engine built-in service account. This may be because the Compute Engine instance does not have the correct permission scopes specified: Could not refresh access token: Unsuccessful response status code. Request failed with status code 403
```

The result is that I'm seeing a lot of Executions that don't complete.

**Comment by slimslenderslacks** [comment]
So, there are two issues that I'm wondering about here:

1.  how quickly should the skill skip the Repo because there was no Dockerfile present?
2.  those errors are preventing the skill from finishing successfully

**Comment by cdupuis** [comment]
I'm unable to recreate this problem. If I configure an incorrect Dockerfile path, the skill or rather kaniko exits immediately and the skill execution gets marked as error within seconds. 

Here's the log output:

```
2020-05-09 15:26:29.714 INFO: Error: error resolving dockerfile path: please provide a valid path to a Dockerfile within the build context with --dockerfile
```

Link to full log: https://go.atomist.com/log/T7GMF5USG/bd507016-bc74-461b-baa9-40fa80a808b9/N31hrDBWqMuv6A5tHhLLW

I think that addresses your number 1. @slimslenderslacks. The skill exists immediately when the configured Dockerfile can't be found. 

Since I can't recreate the error you are seeing and I don't have any more details to go on, I can't tell why you're seeing 2. But my guess is that there is something else wrong in that skill configuration. Happy to look into that if you can give me a link to a skill configuration where this fails.

**Comment by slimslenderslacks** [comment]
I'll have to invite you to this team so you can investigate.  The container does exit after 30 minutes and so the skill eventually did get marked as having failed.  The most recent failed log is https://go.atomist.com/log/AEIB5886C/6397a6ef-7995-45a8-8d90-fe00ad9fce76/vq4dpa35PVvxfm0ykFx5C - it's running on this Repo:  https://github.com/slimslender/elephants

**Comment by slimslenderslacks** [comment]
https://github.com/atomist-skills-configuration/AEIB5886C-skill-configuration/blob/master/atomist_docker-build-skill.yml
I think I've sent you an invite

**Comment by slimslenderslacks** [comment]
By the way, I haven't this in any of the workspaces I use regularly.  I haven't tried to reconfigure this workspace in case we need to investigate it's state

**Comment by cdupuis** [comment]
@slimslenderslacks I do see the following error in this log as well:

```
Error: error resolving dockerfile path: please provide a valid path to a Dockerfile within the build context with --dockerfile
```

But I also see as you describe in this issue:

```
[error] Error occurred sending message: 403 undefined: Getting metadata from plugin failed with error: Could not refresh access token: A Forbidden error was returned while attempting to retrieve an access token for the Compute Engine built-in service account. This may be because the Compute Engine instance does not have the correct permission scopes specified: Could not refresh access token: Unsuccessful response status code. Request failed with status code 403
```

Those errors seem to be coming out of the attempt to write something to stack driver. I'll investigate.

**Comment by cdupuis** [comment]
Issue moved to atomist-skills/skill-runner#12
